spring:
  #http  配置访问本地资源路径
  mvc:
    static-path-pattern: /**
  profiles:
  freemarker:
    allow-request-override: true
    cache: true
    allow-session-override: true
    charset: utf-8
    content-type: text/html
    #配置后缀
    suffix: .ftl
    check-template-location: true
    #配置模板所在的地方
    template-loader-path: classpath:/templates/
    request-context-attribute: request

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url需要加时区serverTimezone=UTC 47.92.175.80
    url: jdbc:mysql://47.92.175.80:3306/qmxmh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    #配置连接池
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    #页面热部署
  thymeleaf:
    cache: false
    #配置静态资源路径
  resources:
    static-locations: classpath:/static/,file:D:/images/qmx/image,file:C:/images/qmx/image

  #类热部署
  devtools:
    restart:
      enabled: true
      #设置重启的目录
     # additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
     # exclude:  WEB-INF


      #输入到控制台
  output:
    ansi:
      enabled: always

    #文件上传
  servlet:
    multipart:
      #总文件大小
      max-request-size: 10MB
      #单个文件大小
      max-file-size: 5MB

#日志
logging:
#  config: classpath:log4j2.yml

  register-shutdown-hook: true
#配置端口
server:
  port: 80
  error:
    path: /error


mybatis:
  #扫描的实体类
  type-aliases-package: com.qmxmh.demo.pojo
  #扫描实现接口的xml
  mapper-locations: classpath:mapping/*.xml

#分页插件
pagehelper:
      reasonable: true
      support-methods-arguments: true
      page-size-zero: true
      helper-dialect: mysql

